# Generated by Django 3.2 on 2021-04-17 08:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(blank=True, default='', verbose_name='Текст')),
                ('date_add', models.DateTimeField(default=datetime.datetime(2021, 4, 18, 8, 23, 30, 695678, tzinfo=utc), verbose_name='Время создания')),
                ('important', models.BooleanField(default=False, verbose_name='Важная записи')),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('activity', models.IntegerField(choices=[(0, 'Активно'), (1, 'Отложено'), (2, 'Выполнено')], default=0, verbose_name='Статус задачи')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
